version: '3.8'

services:

  db:
    image: mariadb:10.5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    env_file: .env

  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/diary
      - ./docker/web/php.ini:/usr/local/etc/php/php.ini
      - ./docker/web/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/web/msmtprc:/etc/msmtprc
      - ./log/xdebug:/var/log/xdebug
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    depends_on:
      - db
    ports:
      - 8033:80
    volumes:
      - './docker/phpmyadminSession:/sessions'

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/diary
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - db

  mailhog:
    image: mailhog/mailhog
    environment:
      MH_MAILDIR_PATH: /tmp
      MH_STORAGE: maildir
      MH_AUTH_FILE: /home/mailhog/auth
      # 25ポートにすると落ちるのでAlpine Linuxの関係で何かありそう
    #      MH_SMTP_BIND_ADDR: 0.0.0.0:25
    ports:
      - 8025:8025
    volumes:
      - ./logs/maildir:/tmp
      - ./docker/mailhog_auth.txt:/home/mailhog/auth

volumes:
  db-volume: