name: deploy-to-h1deblog.com

on:
  push:
    tags:
      - blog-**

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: h1deblog.com
    steps:
      - name: ssh
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
        run: |
          echo "$SECRET_KEY" > secret_key
          chmod 600 secret_key
          ssh -o StrictHostKeyChecking=no ${USER}@${HOST} -i secret_key  -p 10022 "cd /home/h1deserver/h1deblog.com/app_source/diary && sh ./.github/workflows/deploy.sh"
